name: Build and push docker images

on:
  workflow_call:
    inputs:
      services:
        description: "Stringified JSON object listing docker build parameters"
        required: true
        type: string
        default: >-
          {
            "include": [
              {
                "context": ".",
                "tags": "registry.org/user:v1.0.0",
                "target": "",
                "file": "Dockerfile",
                "build-args": ""
              }
            ]
          }
    secrets:
      build_secrets:
        description: "Docker build secrets"
        required: false
      doctl_token:
        description: "DigitalOcean docker registry access token"
        required: true
jobs:
  dockerbuild:
    name: Build and push docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(inputs.services)}}
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.doctl_token }}
      - name: Login to the DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.tags }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.tags }}-
      - name: Build the ${{ matrix.tags }}
        uses: docker/build-push-action@v2
        with:
          push: true
          target: ${{ matrix.target }}
          tags: ${{ matrix.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          file: ${{ matrix.file }}
          build-args: ${{ matrix.build-args }}
          context: ${{ matrix.context }}
          secrets: ${{ secrets.build_secrets }}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
